### ISSUE TITLE
emacs-bin-master.tar.gz not found?

### ISSUE THREAD

**Issue by tsuu32** [npostavs/emacs-travis#3]
Thanks for such a great CI for emacs package!

I found EMACS_VERSION=master build always failed.
Please see https://travis-ci.org/tsuu32/quelpa-use-package/builds/659732059?utm_medium=notification&utm_source=github_status.

I think Currently emacs-bin-master.tar.gz not found.

and followning travis.yml in README
```
env:
  matrix:
    - EMACS_VERSION=23.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master
```
should be 
```
env:
  jobs:
    - EMACS_VERSION=23.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=master

jobs:
  allow_failures:
    - env: EMACS_VERSION=master
```
